##################
## GENERAL
##################
project_id = "nextjs_spesen" # WARNING: Project name must be unique



##################
## API
##################
[api]
enabled = true
port = 54321
max_rows = 1000
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]



##################
## Database
##################
[db]
port = 54322
shadow_port = 54320
major_version = 15 # WARNING: fit remote version! (`SHOW server_version;`)



##################
## Dashboard
##################
[studio]
enabled = true
port = 54323
api_url = "http://spaddevmarcel"



##################
## Emails
##################
[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326




##################
## Storage
##################
[storage]
enabled = true
file_size_limit = "50MiB"



##################
## Authentication
##################
[auth]
enabled = true
site_url = "env(SUPABASE_AUTH_SITE_URL)"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_manual_linking = false
enable_signup = true

[auth.external.keycloak]
enabled = true
client_id = "supabase"
secret = "env(SUPABASE_AUTH_KEYCLOAK_SECRET)"
redirect_uri = "env(SUPABASE_AUTH_CALLBACK_ENDPOINT)"
url = "env(SUPABASE_AUTH_KEYCLOAK_REALM_URL)"
skip_nonce_check = false



##################
## Disabled Features
##################

# WARNING: 
# If you wan't to enable, read the docs for minimal config
# DOCS: https://supabase.com/docs/guides/local-development/cli/config 

[analytics]
enabled = false

[db.pooler]
enabled = false

[realtime]
enabled = false
