/**
 * Author: Marcel Maier
 *
 * NOTE:
 * In this file we use our database types generated by supabase cli,
 * and give them meaningful names that we can use troughout the entire application.
 */

import { Database, Tables } from '@/lib/supabase/types_db'

/*
 * NOTE: Generic Helpers
 */

// Helper type to ensure the string literal matches a valid enum value
export type ValidateLiteral<T, U extends T> = U;

// Helper type to ensure all enums are set in a Record
export type EnsureAll<T extends string, U extends Record<T, string>> = {
    [K in T]: K extends keyof U ? U[K] : never;
};

export type RevalidationPaths = null | string | string[]

export type DBResult<T> = Promise<{ data: T | null; error: Error | null }>


/*
 * NOTE: Items
 */

export type Item = Tables<'shopping_items'>;
export type ItemType = Database['public']['Enums']['shopping_item_types']

/*
 * NOTE: Recepies
 */

export type Recepie = Tables<'recepies'>;


