
create type "public"."shopping_item_types" as enum ('Lebensmittel', 'Trinken', 'Haushalt', 'Katzen');

create table "public"."recepies" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "ingredients" uuid not null default gen_random_uuid()
);


alter table "public"."recepies" enable row level security;

create table "public"."recepies_ingredients" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "recepie" uuid default gen_random_uuid(),
    "ingredient" uuid default gen_random_uuid()
);


alter table "public"."recepies_ingredients" enable row level security;

create table "public"."shopping_items" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "order" bigint,
    "type" shopping_item_types
);


alter table "public"."shopping_items" enable row level security;

create table "public"."shopping_stores" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null
);


alter table "public"."shopping_stores" enable row level security;

CREATE UNIQUE INDEX recepies_ingredients_pkey ON public.recepies_ingredients USING btree (id);

CREATE UNIQUE INDEX recepies_name_key ON public.recepies USING btree (name);

CREATE UNIQUE INDEX recepies_pkey ON public.recepies USING btree (id);

CREATE UNIQUE INDEX shopping_items_name_key ON public.shopping_items USING btree (name);

CREATE UNIQUE INDEX shopping_items_pkey ON public.shopping_items USING btree (id);

CREATE UNIQUE INDEX shopping_stores_name_key ON public.shopping_stores USING btree (name);

CREATE UNIQUE INDEX shopping_stores_pkey ON public.shopping_stores USING btree (id);

alter table "public"."recepies" add constraint "recepies_pkey" PRIMARY KEY using index "recepies_pkey";

alter table "public"."recepies_ingredients" add constraint "recepies_ingredients_pkey" PRIMARY KEY using index "recepies_ingredients_pkey";

alter table "public"."shopping_items" add constraint "shopping_items_pkey" PRIMARY KEY using index "shopping_items_pkey";

alter table "public"."shopping_stores" add constraint "shopping_stores_pkey" PRIMARY KEY using index "shopping_stores_pkey";

alter table "public"."recepies" add constraint "recepies_name_key" UNIQUE using index "recepies_name_key";

alter table "public"."recepies_ingredients" add constraint "recepies_ingredients_ingredient_fkey" FOREIGN KEY (ingredient) REFERENCES shopping_items(id) not valid;

alter table "public"."recepies_ingredients" validate constraint "recepies_ingredients_ingredient_fkey";

alter table "public"."recepies_ingredients" add constraint "recepies_ingredients_recepie_fkey" FOREIGN KEY (recepie) REFERENCES recepies(id) not valid;

alter table "public"."recepies_ingredients" validate constraint "recepies_ingredients_recepie_fkey";

alter table "public"."shopping_items" add constraint "shopping_items_name_key" UNIQUE using index "shopping_items_name_key";

alter table "public"."shopping_stores" add constraint "shopping_stores_name_key" UNIQUE using index "shopping_stores_name_key";

grant delete on table "public"."recepies" to "anon";

grant insert on table "public"."recepies" to "anon";

grant references on table "public"."recepies" to "anon";

grant select on table "public"."recepies" to "anon";

grant trigger on table "public"."recepies" to "anon";

grant truncate on table "public"."recepies" to "anon";

grant update on table "public"."recepies" to "anon";

grant delete on table "public"."recepies" to "authenticated";

grant insert on table "public"."recepies" to "authenticated";

grant references on table "public"."recepies" to "authenticated";

grant select on table "public"."recepies" to "authenticated";

grant trigger on table "public"."recepies" to "authenticated";

grant truncate on table "public"."recepies" to "authenticated";

grant update on table "public"."recepies" to "authenticated";

grant delete on table "public"."recepies" to "service_role";

grant insert on table "public"."recepies" to "service_role";

grant references on table "public"."recepies" to "service_role";

grant select on table "public"."recepies" to "service_role";

grant trigger on table "public"."recepies" to "service_role";

grant truncate on table "public"."recepies" to "service_role";

grant update on table "public"."recepies" to "service_role";

grant delete on table "public"."recepies_ingredients" to "anon";

grant insert on table "public"."recepies_ingredients" to "anon";

grant references on table "public"."recepies_ingredients" to "anon";

grant select on table "public"."recepies_ingredients" to "anon";

grant trigger on table "public"."recepies_ingredients" to "anon";

grant truncate on table "public"."recepies_ingredients" to "anon";

grant update on table "public"."recepies_ingredients" to "anon";

grant delete on table "public"."recepies_ingredients" to "authenticated";

grant insert on table "public"."recepies_ingredients" to "authenticated";

grant references on table "public"."recepies_ingredients" to "authenticated";

grant select on table "public"."recepies_ingredients" to "authenticated";

grant trigger on table "public"."recepies_ingredients" to "authenticated";

grant truncate on table "public"."recepies_ingredients" to "authenticated";

grant update on table "public"."recepies_ingredients" to "authenticated";

grant delete on table "public"."recepies_ingredients" to "service_role";

grant insert on table "public"."recepies_ingredients" to "service_role";

grant references on table "public"."recepies_ingredients" to "service_role";

grant select on table "public"."recepies_ingredients" to "service_role";

grant trigger on table "public"."recepies_ingredients" to "service_role";

grant truncate on table "public"."recepies_ingredients" to "service_role";

grant update on table "public"."recepies_ingredients" to "service_role";

grant delete on table "public"."shopping_items" to "anon";

grant insert on table "public"."shopping_items" to "anon";

grant references on table "public"."shopping_items" to "anon";

grant select on table "public"."shopping_items" to "anon";

grant trigger on table "public"."shopping_items" to "anon";

grant truncate on table "public"."shopping_items" to "anon";

grant update on table "public"."shopping_items" to "anon";

grant delete on table "public"."shopping_items" to "authenticated";

grant insert on table "public"."shopping_items" to "authenticated";

grant references on table "public"."shopping_items" to "authenticated";

grant select on table "public"."shopping_items" to "authenticated";

grant trigger on table "public"."shopping_items" to "authenticated";

grant truncate on table "public"."shopping_items" to "authenticated";

grant update on table "public"."shopping_items" to "authenticated";

grant delete on table "public"."shopping_items" to "service_role";

grant insert on table "public"."shopping_items" to "service_role";

grant references on table "public"."shopping_items" to "service_role";

grant select on table "public"."shopping_items" to "service_role";

grant trigger on table "public"."shopping_items" to "service_role";

grant truncate on table "public"."shopping_items" to "service_role";

grant update on table "public"."shopping_items" to "service_role";

grant delete on table "public"."shopping_stores" to "anon";

grant insert on table "public"."shopping_stores" to "anon";

grant references on table "public"."shopping_stores" to "anon";

grant select on table "public"."shopping_stores" to "anon";

grant trigger on table "public"."shopping_stores" to "anon";

grant truncate on table "public"."shopping_stores" to "anon";

grant update on table "public"."shopping_stores" to "anon";

grant delete on table "public"."shopping_stores" to "authenticated";

grant insert on table "public"."shopping_stores" to "authenticated";

grant references on table "public"."shopping_stores" to "authenticated";

grant select on table "public"."shopping_stores" to "authenticated";

grant trigger on table "public"."shopping_stores" to "authenticated";

grant truncate on table "public"."shopping_stores" to "authenticated";

grant update on table "public"."shopping_stores" to "authenticated";

grant delete on table "public"."shopping_stores" to "service_role";

grant insert on table "public"."shopping_stores" to "service_role";

grant references on table "public"."shopping_stores" to "service_role";

grant select on table "public"."shopping_stores" to "service_role";

grant trigger on table "public"."shopping_stores" to "service_role";

grant truncate on table "public"."shopping_stores" to "service_role";

grant update on table "public"."shopping_stores" to "service_role";

